### ISSUE TITLE
analysis: IsFileGenerated to ignore testdata directory?

### ISSUE THREAD

**Issue by bradleyfalzon** [shurcooL/go#26]
Hey,

If `IsFileGenerated` already ignores vendor directories, would you be interested in also ignoring `testdata` directories?

I'd like to use this function via CLI, but to also ignore `testdata` directories for https://github.com/bradleyfalzon/gopherci/issues/57, happy to handle this myself, but I thought I'd ask if ignoring `testdata` was in scope of this function considering it's already ignoring `vendor` directories.

**Comment by shurcooL** [comment]
Hey @bradleyfalzon, thanks for asking.

It's more accurate to say that `analysis.IsFileGenerated` reports files inside `vendor` directories as generated. It doesn't ignore them, it includes them.

It seems that you want to use `analysis.IsFileGenerated` in order to ignore generated files as well as `testdata` directories from being tested by GopherCI, right?

I think you should write your own func that _uses_ `analysis.IsFileGenerated` to achieve what you want. You'd probably also want to ignore things that begin with `.` or `_`.

It would be incorrect for `analysis.IsFileGenerated` to return true on anything in `testdata`. Its job is to report .go files that are known to be generated or in other ways a non-canonical source (and that's why `vendor` is included, because by definition, vendored code is a copy, not the canonical handcrafted source). But it can't know for certain whether files inside `testdata` are generated, so it returns false.

**Comment by bradleyfalzon** [comment]
Thanks, I think the missing piece of information was `known to be generated or in other ways a non-canonical source`, so thanks for clarifying.
