### ISSUE TITLE
generated: Should have API that accepts io.Reader.

### ISSUE THREAD

**Issue by monicaq** [shurcooL/go#31]
I want to check files from a  [go/build Context](https://godoc.org/go/build#Context).  In some scenarios, these files may not be in the file system. Please add io.Writer API.

**Comment by shurcooL** [comment]
Agreed. This is both easy to support, and necessary for .go files that are not on real filesystem.

I was planning on doing this, but held off until later, because we need to decide on an API.

I see two options:

1. A new function that takes `io.Reader`.

2. Modify existing function, make it similar to [`parser.ParseFile`](https://godoc.org/go/parser#ParseFile), but reduced to only support `io.Reader`.

    ```
    (filename string, src io.Reader)
    ```

    > If src != nil, ParseFile parses the source from src and the filename is unused. The type of the argument for the src parameter must be io.Reader. If src == nil, ParseFile parses the file specified by filename.

**Comment by shurcooL** [comment]
@monicaq, do you have any preferences between those 2 options?

**Comment by shurcooL** [comment]
I've implemented both approaches to make it easier to compare them (because I can't tell off the top of my head which is better, they seem to have nearly equal trade-offs in my mind).

## ParseFile with 2 parameters (inspired by go/parser.ParseFile)

![image](https://cloud.githubusercontent.com/assets/1924134/25059814/a62a4bce-215b-11e7-867a-134ed555f885.png)

## New ParseReader method

![image](https://cloud.githubusercontent.com/assets/1924134/25059872/0353c856-215d-11e7-81cc-4ebdc2d2c199.png)

**Comment by shurcooL** [comment]
It's really hard to make a choice between the two, because there is no clear winner. There hasn't been any input on this topic so far.

In order to make progress, I have to make a decision. I will go with a new `Parse(io.Reader)` function for now, and revisit this later if needed.
